import { LocalizationLibrary } from "./app.interfeces";


const localizationLibrary: LocalizationLibrary = {
  en: {
    strings: {
      'About project': 'About project',
      'About course': 'About course',
      'Developer': 'Developer',
      'Login': 'Login',
      'Sign up': 'Sign up',
      'Log out': 'Log out',
      'Error': 'Error',
      'Got it': 'Got it',
      '*Please submit title changes': '*Please submit title changes',
      'Description': 'Description:',
      'Current task executor': 'Current executor',
      'Change Name or Login': 'Change Name or Login',
      'Enter new Name': 'Enter new Name',
      'Enter your Name': 'Enter your Name',
      'Enter new login': 'Enter new login',
      'Enter login': 'Enter login',
      'Enter your login': 'Enter your login',
      'Change Password': 'Change Password',
      'Enter password': 'Enter password',
      'Enter a new password': 'Enter a new password',
      'Repeat new password': 'Repeat new password',
      'Enter current password': 'Enter current password',
      'Save changes': 'Save changes',
      'Cancel': 'Cancel',
      'Remove User Account': 'Remove User Account',
      'Enter a board title': 'Enter a board title',
      'Invite participants': 'Invite participants',
      'Choose a name': 'Choose a name',
      'Enter a column title': 'Enter a column title',
      'Task title': 'Task title',
      'Select an excecutor': 'Select an excecutor',
      'Enter a task description': 'Enter a task description',
      'Create your first project': 'Create your first project',
      'Owner': 'Owner',
      'Participants': 'Participants',
      'Your own projects': 'Your own projects',
      'Projects you were invited to': 'Projects you were invited to',
      'Other projects': 'Other projects',
      'Page not found': 'Page not found',
      'Task search': 'Task search',
      'Creator': 'Creator',
      'You must enter a': 'You must enter a',
      'Min length of': 'Min length of',
      'Max length of': 'Max length of',
      'Allowed symbols for': 'Allowed symbols for',
      'Passwords do not match': 'Passwords do not match',
      'Not valid': 'Not valid',
      'chars': 'chars',
      'column title': 'column title',
      'board title': 'board title',
      'task title': 'task title',
      'task description': 'task description',
      'name': 'name',
      'login': 'login',
      'password': 'password',
      'search request': 'search request',
    },
    articles: {
      'welcome title': 'Welcome to Project Management Application (PMA)!',
      'project description': 'Many words about project',
      'course description': 'Many words about course',
      'developer description': 'Many words about developer',
      'error menu title': 'Oops... Something went wrong!',
    },
  },
  ru: {
    strings: {
      'About project': 'O проекте',
      'About course': 'O курсе',
      'Developer': 'Разработчик',
      'Login': 'Войти',
      'Sign up': 'Регистрация',
      'Log out': 'Выйти',
      'Error': 'Ошибка',
      'Got it': 'Понятно',
      '*Please submit title changes': '*Пожалуйста, подтвердите изменения',
      'Description': 'Описание',
      'Current task executor': 'Текущий исполнитель',
      'Change Name or Login': 'Измените имя или логин',
      'Enter new Name': 'Введите новое имя',
      'Enter your Name': 'Введите Ваше имя',
      'Enter new login': 'Введите новый логин',
      'Enter login': 'Введите логин',
      'Enter your login': 'Введите свой логин',
      'Change Password': 'Изменить пароль',
      'Enter password': 'Введите пароль',
      'Enter a new password': 'Введите новый пароль',
      'Repeat new password': 'Повторите новый пароль',
      'Enter current password': 'Введите текущий пароль',
      'Save changes': 'Сохранить изменения',
      'Cancel': 'Отмена',
      'Remove User Account': 'Удалить учетную запись пользователя',
      'Enter a board title': 'Введите название проекта',
      'Invite participants': 'Пригласить участников',
      'Choose a name': 'Выберите имя',
      'Enter a column title': 'Введите заголовок столбца',
      'Task title': 'Название задачи',
      'Select an excecutor': 'Выберите исполнителя',
      'Enter a task description': 'Введите описание задачи',
      'Create your first project': 'Создайте свой первый проект',
      'Owner': 'Владелец',
      'Participants': 'Участники',
      'Your own projects': 'Ваши собственные проекты',
      'Projects you were invited to': 'Проекты, в которые вы были приглашены',
      'Other projects': 'Другие проекты',
      'Page not found': 'Страница не найдена',
      'Task search': 'Поиск задачи',
      'Creator': 'Создатель',
      'You must enter a': 'Вы должны ввести',
      'Min length of': 'Мин длина',
      'Max length of': 'Максимальная длина',
      'Allowed symbols for': 'Разрешенные символы для',
      'Passwords do not match': 'Пароли не совпадают',
      'Not valid': 'Недействительно',
      'chars': 'символа',
      'column title': 'заголовок столбца',
      'board title': 'название проекта',
      'task title': 'Название задачи',
      'task description': 'описания задачи',
      'name': 'имя',
      'login': 'логина',
      'password': 'пароля',
      'search request': 'запроса на поиск',

    },
    articles: {
      'welcome title': 'Добро пожаловать в приложение для управления проектами (PMA)!',
      'project description': 'Много слов о проекте',
      'course description': 'Много слов о курсе',
      'developer description': 'Много слов о разработчике',
      'error menu title': 'Упс! Что-то пошло не так!',
    },
  },
}

export { localizationLibrary };
